apiVersion: apps/v1
kind: Deployment                 # Type of Kubernetes resource
metadata:
  name: go-k8s           # Name of the Kubernetes resource
spec:
  replicas: 1                    # Number of pods to run at any given time
  selector:
    matchLabels:
      app: go-k8s        # This deployment applies to any Pods matching the specified label
  template:                      # This deployment will create a set of pods using the configurations in this template
    metadata:
      labels:                    # The labels that will be applied to all of the pods in this deployment
        app: go-k8s
    spec:                        # Spec for the container which will run in the Pod
      containers:
      - name: go-k8s
        image: hsiri/go-k8s:1.0.0
        imagePullPolicy: Always
        ports:
          - containerPort: 8080  # Should match the port number that the Go application listens on
        envFrom:
        - secretRef:
            name: go-k8s-credentials
        livenessProbe:           # To check the health of the Pod
          httpGet:
            path: /healthcheck
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 15
          timeoutSeconds: 5
        readinessProbe:          # To check if the Pod is ready or not
          httpGet:
            path: /healthcheck
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          timeoutSeconds: 1