apiVersion: v1
kind: Service                    # Type of kubernetes resource
metadata:
  name: go-k8s   # Name of the resource
spec:
  type: LoadBalancer                 # If you're deploying on cloud, you can use `type: LoadBalancer`. It will automatically provision a load balancer with the cloud provider that will route traffic to your application.
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: go-k8s          # Map any pod with name go-k8s to this service